environments:
	bootcamp:
		name: Bootcamp Profile
	student:
		name: Student Profile
		

spring:
	profiles: bootcamp
prop:
	server:
		- 123
		- 456
	
spring:
	profiles: bootcamp
prod:
	servers:
		-abc
		-def
	

		